#
# This is the Docker image that gets published to DockerHub.
# Goreleaser takes care of building the binary.
#
FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

COPY publiccode-parser /usr/local/bin/publiccode-parser

# git and openssh-client are needed by CircleCI when using
# publiccode-parser-orb, which uses this image.
RUN apk --no-cache add git openssh-client

ENTRYPOINT ["/usr/local/bin/publiccode-parser"]
CMD ["files/publiccode.yml"]
