#
# This is the Docker image that gets published to DockerHub.
# Goreleaser takes care of building the binary.
#
FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

COPY publiccode-parser /usr/local/bin/publiccode-parser

# git and openssh-client are needed by CircleCI when using
# publiccode-parser-orb, which uses this image.
RUN apk --no-cache add git openssh-client

ENTRYPOINT ["/usr/local/bin/publiccode-parser"]
CMD ["files/publiccode.yml"]
