on: [push, pull_request]

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout 3m --verbose
